version: '3.1'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"